seed: ???
task_name: vision

data_name: &data_name cifar10
data_config:
  dataset_name: *data_name
  batch_size: 64
  num_workers: 6

model_name: &model_name resnet18
model_config:
  model_name: *model_name
  optimizer_name: adam
  learning_rate: 2.0e-5
  weight_decay: 5.0e-4

trainer:
  max_epochs: 100
  gpu: [ 0 ]

experiments:
  - seeds:
      - seed: 2021
      - seed: 2022
      - seed: 2023
      - seed: 2024
      - seed: 2025